name: paketo-nodejs

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run-buildpack-and-push-oci-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: buildpacks-action
        # You may pin to the exact commit or the version.
        uses: mamezou-tech/buildpacks-action@v0.7.0
        with:
          # Name of container image
          image: ${{ env.IMAGE_NAME }}
          # Tag of container image
          #tag: # optional, default is latest
          # Path to target application, defaults to the current directory
          #path: # optional, default is .
          # Builder to use
          #builder: paketobuildpacks/builder:base
          builder: paketobuildpacks/builder:full
          # Custom buildpacks to use
          buildpacks: gcr.io/paketo-buildpacks/nodejs
          # Build-time environment variables
          # env: # optional
          # Read build-time environment variables from these files
          # env_files: # optional
          publish: true

